### PR TITLE
Fixes: traefik.toml [#18] and configuration files [#19]

### PR DESCRIPTION
**Pull request by k33rs**
Fixed according to comments.

Edit: role-based node constraint [#22]

### CODE REVIEW

**Comment by k33rs** [comment]
Comment by Tomas: check that traefik works out of the box, i.e. even without the user filling the traefik-template.toml nor renaming the file to traefik.toml.

**Review by chicco785 — APPROVED** [review]
LGTM

**Comment by taliaga** [comment]
@chersicm note the compose config remained with
```
traefik_config:
    file: ./traefik/traefik.toml
```
but the file remained as `traefik-template.toml`.

**Comment by k33rs** [comment]
Yes, the idea is that the user edits and renames the file. I will include
instructions in the docs.

**Comment by taliaga** [comment]
But, how about what we discussed yesterday?

**Comment by k33rs** [comment]
Fixed

**Pull request merged**
